In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import root_mean_squared_error

In [2]:
df = pd.read_csv('../Car-details.csv')
df.sample(5)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
5694,Ford Fiesta 1.4 Duratec ZXI,2008,136000,200185,Petrol,Individual,Manual,First Owner,16.6 kmpl,1388 CC,68 bhp,"16.3@ 2,000(kgm@ rpm)",5.0
73,Hyundai i10 Magna,2011,235000,60000,Petrol,Individual,Manual,Second Owner,20.36 kmpl,1197 CC,78.9 bhp,111.7Nm@ 4000rpm,5.0
2355,Maruti Swift ZXI Plus,2018,720000,20000,Petrol,Individual,Manual,First Owner,22.0 kmpl,1197 CC,81.80 bhp,113Nm@ 4200rpm,5.0
1642,Maruti Swift Dzire VXI,2016,500000,30000,Petrol,Individual,Manual,First Owner,20.85 kmpl,1197 CC,83.14 bhp,115Nm@ 4000rpm,5.0
6284,Maruti Ertiga SHVS VDI,2019,925000,50000,Diesel,Dealer,Manual,First Owner,24.52 kmpl,1248 CC,88.5 bhp,200Nm@ 1750rpm,7.0

In [3]:
df['mileage'] = df['mileage'].str.extract('(\d+\.?\d*)').astype(float)
df['engine'] = df['engine'].str.extract('(\d+\.?\d*)').astype(float)
df['max_power'] = df['max_power'].str.extract('(\d+\.?\d*)').astype(float)
df['torque'] = df['torque'].str.extract('(\d+\.?\d*)').astype(float)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   object
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   object
 5   seller_type    8128 non-null   object
 6   transmission   8128 non-null   object
 7   owner          8128 non-null   object
 8   mileage        7907 non-null   object
 9   engine         7907 non-null   object
 10  max_power      7913 non-null   object
 11  torque         7906 non-null   object
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB

In [6]:
df.isna().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [7]:
df.shape

(8128, 13)

In [12]:
for col in df.select_dtypes(include='O').columns:
    print(f'Column: {col}')
    print(f'Cardinality: {df[col].nunique()}')
    print(df[col].unique())
    print(df[col].value_counts(normalize=True))
    print()

Column: name
Cardinality: 2058
['Maruti Swift Dzire VDI' 'Skoda Rapid 1.5 TDI Ambition'
 'Honda City 2017-2020 EXi' ... 'Tata Nexon 1.5 Revotorq XT'
 'Ford Freestyle Titanium Plus Diesel BSIV'
 'Toyota Innova 2.5 GX (Diesel) 8 Seater BS IV']
name
Maruti Swift Dzire VDI              0.015871
Maruti Alto 800 LXI                 0.010089
Maruti Alto LXi                     0.008735
BMW X4 M Sport X xDrive20d          0.007628
Maruti Swift VDI                    0.007505
                                      ...
Maruti 800 DX BSII                  0.000123
Ford Figo Aspire Titanium Diesel    0.000123
Hyundai Verna CRDi 1.6 SX           0.000123
Maruti Baleno Alpha Diesel          0.000123
Tata New Safari Dicor VX 4X2        0.000123
Name: proportion, Length: 2058, dtype: float64

Column: fuel
Cardinality: 4
['Diesel' 'Petrol' 'LPG' 'CNG']
fuel
Diesel    0.541585
Petrol    0.446727
CNG       0.007013
LPG       0.004675
Name: proportion, dtype: float64

Column: seller_type
Cardinality: 3
['Individual' 'Dealer' 'Trustmark Dealer']
seller_type
Individual          0.832431
Dealer              0.138533
Trustmark Dealer    0.029035
Name: proportion, dtype: float64

Column: transmission
Cardinality: 2
['Manual' 'Automatic']
transmission
Manual       0.870817
Automatic    0.129183
Name: proportion, dtype: float64

Column: owner
Cardinality: 5
['First Owner' 'Second Owner' 'Third Owner' 'Fourth & Above Owner'
 'Test Drive Car']
owner
First Owner             0.650714
Second Owner            0.258981
Third Owner             0.068282
Fourth & Above Owner    0.021407
Test Drive Car          0.000615
Name: proportion, dtype: float64

Column: mileage
Cardinality: 393
['23.4 kmpl' '21.14 kmpl' '17.7 kmpl' '23.0 kmpl' '16.1 kmpl' '20.14 kmpl'
 '17.3 km/kg' '23.59 kmpl' '20.0 kmpl' '19.01 kmpl' '17.3 kmpl'
 '19.3 kmpl' nan '18.9 kmpl' '18.15 kmpl' '24.52 kmpl' '19.7 kmpl'
 '22.54 kmpl' '21.0 kmpl' '25.5 kmpl' '26.59 kmpl' '21.5 kmpl' '20.3 kmpl'
 '21.4 kmpl' '24.7 kmpl' '18.2 kmpl' '16.8 kmpl' '24.3 kmpl' '14.0 kmpl'
 '18.6 kmpl' '33.44 km/kg' '23.95 kmpl' '17.0 kmpl' '20.63 kmpl'
 '13.93 kmpl' '16.0 kmpl' '17.8 kmpl' '18.5 kmpl' '12.55 kmpl'
 '12.99 kmpl' '14.8 kmpl' '13.5 kmpl' '26.0 kmpl' '20.65 kmpl' '27.3 kmpl'
 '11.36 kmpl' '17.68 kmpl' '14.28 kmpl' '18.53 kmpl' '14.84 kmpl'
 '21.12 kmpl' '20.36 kmpl' '21.27 kmpl' '18.16 kmpl' '22.0 kmpl'
 '25.1 kmpl' '20.51 kmpl' '21.66 kmpl' '25.2 kmpl' '22.9 kmpl'
 '16.02 kmpl' '20.54 kmpl' '22.77 kmpl' '15.71 kmpl' '23.1 kmpl'
 '19.02 kmpl' '19.81 kmpl' '26.2 km/kg' '16.47 kmpl' '15.04 kmpl'
 '19.1 kmpl' '21.79 kmpl' '18.8 kmpl' '21.21 kmpl' '15.37 kmpl'
 '11.79 kmpl' '19.0 kmpl' '14.3 kmpl' '15.8 kmpl' '15.1 kmpl' '19.09 kmpl'
 '22.32 kmpl' '21.9 kmpl' '14.53 kmpl' '21.63 kmpl' '20.85 kmpl'
 '20.45 kmpl' '19.67 kmpl' '23.01 kmpl' '20.77 kmpl' '17.92 kmpl'
 '17.01 kmpl' '22.37 kmpl' '19.33 kmpl' '9.5 kmpl' '12.83 kmpl'
 '22.48 kmpl' '16.78 kmpl' '14.67 kmpl' '15.0 kmpl' '13.96 kmpl'
 '18.0 kmpl' '12.07 kmpl' '26.21 kmpl' '10.8 kmpl' '16.3 kmpl' '13.6 kmpl'
 '14.74 kmpl' '15.6 kmpl' '19.56 kmpl' '22.69 kmpl' '19.16 kmpl'
 '18.12 kmpl' '12.1 kmpl' '17.5 kmpl' '42.0 kmpl' '20.4 kmpl' '21.1 kmpl'
 '19.44 kmpl' '13.0 kmpl' '21.43 kmpl' '22.95 kmpl' '16.2 kmpl'
 '15.3 kmpl' '28.09 kmpl' '17.4 kmpl' '19.4 kmpl' '26.6 km/kg' '17.6 kmpl'
 '28.4 kmpl' '14.1 kmpl' '25.17 kmpl' '22.74 kmpl' '17.57 kmpl'
 '16.95 kmpl' '19.49 kmpl' '17.21 kmpl' '13.2 kmpl' '14.2 kmpl'
 '26.8 kmpl' '25.4 kmpl' '11.5 kmpl' '27.28 kmpl' '17.97 kmpl' '12.8 kmpl'
 '16.55 kmpl' '12.05 kmpl' '14.07 kmpl' '21.02 kmpl' '11.57 kmpl'
 '17.9 kmpl' '15.96 kmpl' '17.1 kmpl' '17.19 kmpl' '21.01 kmpl'
 '24.0 kmpl' '25.6 kmpl' '21.38 kmpl' '23.84 kmpl' '23.08 kmpl'
 '14.24 kmpl' '20.71 kmpl' '15.64 kmpl' '14.5 kmpl' '16.34 kmpl'
 '27.39 kmpl' '11.1 kmpl' '13.9 kmpl' '20.88 km/kg' '20.92 kmpl'
 '23.8 kmpl' '24.4 kmpl' '15.29 kmpl' '21.19 kmpl' '22.5 kmpl' '19.6 kmpl'
 '23.65 kmpl' '25.32 kmpl' '23.5 kmpl' '16.6 kmpl' '23.9 kmpl' '20.8 kmpl'
 '27.62 kmpl' '12.9 kmpl' '25.44 kmpl' '17.88 kmpl' '22.7 kmpl'
 '17.2 kmpl' '15.42 kmpl' '19.68 kmpl' '18.7 kmpl' '15.4 kmpl'
 '19.34 kmpl' '22.71 kmpl' '25.8 kmpl' '13.7 kmpl' '12.2 kmpl'
 '18.49 kmpl' '9.0 kmpl' '0.0 kmpl' '13.58 kmpl' '10.1 kmpl' '20.5 kmpl'
 '25.0 kmpl' '10.5 kmpl' '22.07 kmpl' '22.3 kmpl' '15.26 kmpl'
 '20.62 kmpl' '27.4 kmpl' '23.2 kmpl' '14.4 kmpl' '18.4 kmpl'
 '30.46 km/kg' '14.02 kmpl' '11.0 kmpl' '20.6 kmpl' '22.05 kmpl'
 '20.2 kmpl' '18.1 kmpl' '22.1 kmpl' '19.87 kmpl' '13.01 kmpl'
 '18.06 kmpl' '26.1 kmpl' '16.52 kmpl' '13.55 kmpl' '24.2 kmpl'
 '25.83 kmpl' '11.2 kmpl' '17.09 kmpl' '21.03 kmpl' '17.45 kmpl'
 '21.64 kmpl' '21.94 km/kg' '13.87 kmpl' '19.98 kmpl' '20.52 kmpl'
 '23.57 kmpl' '11.7 kmpl' '17.43 kmpl' '18.88 kmpl' '13.68 kmpl'
 '11.18 kmpl' '20.89 kmpl' '11.8 kmpl' '19.62 kmpl' '21.7 kmpl'
 '14.9 kmpl' '19.5 kmpl' '10.91 kmpl' '15.7 kmpl' '20.73 kmpl'
 '15.85 kmpl' '20.7 kmpl' '14.23 kmpl' '16.5 kmpl' '17.36 kmpl'
 '12.6 kmpl' '16.36 kmpl' '14.95 kmpl' '16.9 kmpl' '19.2 kmpl'
 '16.96 kmpl' '22.15 kmpl' '18.78 kmpl' '19.61 kmpl' '17.71 kmpl'
 '18.3 kmpl' '19.12 kmpl' '19.72 kmpl' '12.0 kmpl' '11.4 kmpl'
 '23.03 kmpl' '11.07 kmpl' '15.9 kmpl' '17.67 kmpl' '20.46 kmpl'
 '13.1 kmpl' '13.45 km/kg' '24.8 kmpl' '15.73 kmpl' '15.11 kmpl'
 '12.7 kmpl' '21.2 kmpl' '20.38 kmpl' '21.56 kmpl' '13.22 kmpl'
 '14.49 kmpl' '15.05 kmpl' '23.26 kmpl' '15.41 kmpl' '13.8 kmpl'
 '22.27 kmpl' '32.52 km/kg' '14.66 kmpl' '12.12 kmpl' '16.84 kmpl'
 '14.09 kmpl' '14.7 kmpl' '13.4 kmpl' '15.5 kmpl' '13.49 kmpl'
 '11.88 km/kg' '14.6 kmpl' '10.75 kmpl' '24.5 kmpl' '11.74 kmpl'
 '16.07 kmpl' '15.63 kmpl' '26.3 km/kg' '23.7 km/kg' '25.47 kmpl'
 '17.05 kmpl' '23.3 kmpl' '11.9 kmpl' '13.38 kmpl' '20.86 kmpl'
 '19.2 km/kg' '10.9 kmpl' '18.25 kmpl' '15.2 kmpl' '20.37 kmpl'
 '17.8 km/kg' '21.8 kmpl' '11.96 kmpl' '24.04 kmpl' '19.69 kmpl'
 '13.73 kmpl' '21.04 kmpl' '25.01 kmpl' '10.93 kmpl' '10.9 km/kg'
 '24.29 kmpl' '13.44 kmpl' '20.07 kmpl' '21.1 km/kg' '19.08 kmpl'
 '20.34 kmpl' '11.68 kmpl' '12.5 kmpl' '12.3 kmpl' '23.87 kmpl'
 '16.38 kmpl' '17.42 kmpl' '10.0 kmpl' '18.24 kmpl' '10.71 kmpl'
 '19.59 kmpl' '16.7 kmpl' '19.83 kmpl' '21.76 kmpl' '16.05 kmpl'
 '20.28 kmpl' '16.25 kmpl' '16.73 kmpl' '18.48 kmpl' '13.2 km/kg'
 '21.4 km/kg' '14.99 kmpl' '18.76 kmpl' '16.4 kmpl' '19.64 kmpl'
 '14.94 kmpl' '16.6 km/kg' '16.0 km/kg' '17.11 kmpl' '22.8 km/kg'
 '32.26 km/kg' '33.0 km/kg' '12.4 kmpl' '18.44 kmpl' '16.09 kmpl'
 '19.0 km/kg' '12.62 kmpl' '21.13 kmpl' '15.17 kmpl' '21.73 kmpl'
 '21.72 kmpl' '12.85 kmpl' '14.81 kmpl' '13.24 kmpl' '14.4 km/kg'
 '21.49 kmpl' '14.62 kmpl' '26.83 km/kg' '11.45 kmpl' '12.08 kmpl'
 '15.74 kmpl' '11.3 kmpl' '15.1 km/kg' '14.21 kmpl' '11.72 kmpl'
 '16.51 kmpl']
mileage
18.9 kmpl     0.028456
19.7 kmpl     0.021879
18.6 kmpl     0.020741
21.1 kmpl     0.019856
17.0 kmpl     0.016821
                ...
12.5 kmpl     0.000126
23.87 kmpl    0.000126
16.38 kmpl    0.000126
11.72 kmpl    0.000126
16.51 kmpl    0.000126
Name: proportion, Length: 393, dtype: float64

Column: engine
Cardinality: 121
['1248 CC' '1498 CC' '1497 CC' '1396 CC' '1298 CC' '1197 CC' '1061 CC'
 '796 CC' '1364 CC' '1399 CC' '1461 CC' '993 CC' nan '1198 CC' '1199 CC'
 '998 CC' '1591 CC' '2179 CC' '1368 CC' '2982 CC' '2494 CC' '2143 CC'
 '2477 CC' '1462 CC' '2755 CC' '1968 CC' '1798 CC' '1196 CC' '1373 CC'
 '1598 CC' '1998 CC' '1086 CC' '1194 CC' '1172 CC' '1405 CC' '1582 CC'
 '999 CC' '2487 CC' '1999 CC' '3604 CC' '2987 CC' '1995 CC' '1451 CC'
 '1969 CC' '2967 CC' '2497 CC' '1797 CC' '1991 CC' '2362 CC' '1493 CC'
 '1599 CC' '1341 CC' '1794 CC' '799 CC' '1193 CC' '2696 CC' '1495 CC'
 '1186 CC' '1047 CC' '2498 CC' '2956 CC' '2523 CC' '1120 CC' '624 CC'
 '1496 CC' '1984 CC' '2354 CC' '814 CC' '793 CC' '1799 CC' '936 CC'
 '1956 CC' '1997 CC' '1499 CC' '1948 CC' '2997 CC' '2489 CC' '2499 CC'
 '2609 CC' '2953 CC' '1150 CC' '1994 CC' '1388 CC' '1527 CC' '2199 CC'
 '995 CC' '2993 CC' '1586 CC' '1390 CC' '909 CC' '2393 CC' '3198 CC'
 '1339 CC' '2835 CC' '2092 CC' '1595 CC' '2496 CC' '1596 CC' '1597 CC'
 '2596 CC' '2148 CC' '1299 CC' '1590 CC' '2231 CC' '2694 CC' '2200 CC'
 '1795 CC' '1896 CC' '1796 CC' '1422 CC' '1489 CC' '2359 CC' '2197 CC'
 '2999 CC' '1781 CC' '2650 CC' '1343 CC' '2446 CC' '3498 CC' '2198 CC'
 '2776 CC' '1950 CC']
engine
1248 CC    0.128620
1197 CC    0.105223
998 CC     0.057291
796 CC     0.056153
2179 CC    0.049197
             ...
2650 CC    0.000126
2446 CC    0.000126
3498 CC    0.000126
2776 CC    0.000126
1950 CC    0.000126
Name: proportion, Length: 121, dtype: float64

Column: max_power
Cardinality: 322
['74 bhp' '103.52 bhp' '78 bhp' '90 bhp' '88.2 bhp' '81.86 bhp' '57.5 bhp'
 '37 bhp' '67.1 bhp' '68.1 bhp' '108.45 bhp' '60 bhp' '73.9 bhp' nan
 '67 bhp' '82 bhp' '88.5 bhp' '46.3 bhp' '88.73 bhp' '64.1 bhp' '98.6 bhp'
 '88.8 bhp' '83.81 bhp' '83.1 bhp' '47.3 bhp' '73.8 bhp' '34.2 bhp'
 '35 bhp' '81.83 bhp' '40.3 bhp' '121.3 bhp' '138.03 bhp' '160.77 bhp'
 '117.3 bhp' '116.3 bhp' '83.14 bhp' '67.05 bhp' '168.5 bhp' '100 bhp'
 '120.7 bhp' '98.63 bhp' '175.56 bhp' '103.25 bhp' '171.5 bhp' '100.6 bhp'
 '174.33 bhp' '187.74 bhp' '170 bhp' '78.9 bhp' '88.76 bhp' '86.8 bhp'
 '108.495 bhp' '108.62 bhp' '93.7 bhp' '103.6 bhp' '98.59 bhp' '189 bhp'
 '67.04 bhp' '68.05 bhp' '58.2 bhp' '82.85 bhp' '81.80 bhp' '73 bhp'
 '120 bhp' '94.68 bhp' '160 bhp' '65 bhp' '155 bhp' '69.01 bhp'
 '126.32 bhp' '138.1 bhp' '83.8 bhp' '126.2 bhp' '98.96 bhp' '62.1 bhp'
 '86.7 bhp' '188 bhp' '214.56 bhp' '177 bhp' '280 bhp' '148.31 bhp'
 '254.79 bhp' '190 bhp' '177.46 bhp' '204 bhp' '141 bhp' '117.6 bhp'
 '241.4 bhp' '282 bhp' '150 bhp' '147.5 bhp' '108.5 bhp' '103.5 bhp'
 '183 bhp' '181.04 bhp' '157.7 bhp' '164.7 bhp' '91.1 bhp' '400 bhp'
 '68 bhp' '75 bhp' '85.8 bhp' '87.2 bhp' '53 bhp' '118 bhp' '103.2 bhp'
 '83 bhp' '84 bhp' '58.16 bhp' '147.94 bhp' '74.02 bhp' '53.3 bhp'
 '80 bhp' '88.7 bhp' '97.7 bhp' '121.36 bhp' '162 bhp' '140 bhp' '94 bhp'
 '100.57 bhp' '82.9 bhp' '83.11 bhp' '70 bhp' '153.86 bhp' '121 bhp'
 '126.3 bhp' '73.97 bhp' '171 bhp' '69 bhp' '99.6 bhp' '102 bhp' '105 bhp'
 '63 bhp' '79.4 bhp' '97.9 bhp' '63.1 bhp' '66.1 bhp' '110 bhp'
 '174.5 bhp' '53.26 bhp' '73.75 bhp' '67.06 bhp' '64.08 bhp' '37.5 bhp'
 '189.3 bhp' '158.8 bhp' '61.7 bhp' '55.2 bhp' '71.01 bhp' '73.74 bhp'
 '147.9 bhp' '71 bhp' '77 bhp' '121.4 bhp' '113.4 bhp' '47 bhp' '130 bhp'
 '57.6 bhp' '138 bhp' '52.8 bhp' '53.64 bhp' '53.5 bhp' '76.8 bhp'
 '82.4 bhp' '113.42 bhp' '76 bhp' '84.8 bhp' '0' '56.3 bhp' '218 bhp'
 '112 bhp' '92 bhp' '105.5 bhp' '169 bhp' '95 bhp' '72.4 bhp' '115 bhp'
 '152 bhp' '91.2 bhp' '156 bhp' '74.9 bhp' '62 bhp' '105.3 bhp'
 '73.94 bhp' '85.80 bhp' '85 bhp' '118.3 bhp' '72 bhp' '147.51 bhp'
 '58 bhp' '64 bhp' '126.24 bhp' '76.9 bhp' '194.3 bhp' '99.23 bhp'
 '89.84 bhp' '123.7 bhp' '118.35 bhp' '99 bhp' '241 bhp' '136 bhp'
 '261.4 bhp' '104.68 bhp' '37.48 bhp' '104 bhp' '88.50 bhp' '63.12 bhp'
 '91.7 bhp' '102.5 bhp' '177.6 bhp' '45 bhp' '123.37 bhp' '147.8 bhp'
 '184 bhp' '84.48 bhp' '68.07 bhp' '74.96 bhp' '167.6 bhp' '152.87 bhp'
 '112.2 bhp' '83.83 bhp' '197 bhp' '110.4 bhp' '104.55 bhp' '103 bhp'
 '103.3 bhp' '66 bhp' '108.6 bhp' '165 bhp' '163.7 bhp' '116.9 bhp'
 '94.93 bhp' '127 bhp' '198.5 bhp' '179.5 bhp' '120.69 bhp' '121.31 bhp'
 '138.08 bhp' '187.7 bhp' '80.8 bhp' '86.79 bhp' '93.87 bhp' '116.6 bhp'
 '143 bhp' '92.7 bhp' '88 bhp' '58.33 bhp' '78.8 bhp' '64.4 bhp' '125 bhp'
 '139.01 bhp' '254.8 bhp' '181 bhp' '258 bhp' '55.23 bhp' '270.9 bhp'
 '265 bhp' '157.75 bhp' '101 bhp' '186 bhp' '187.4 bhp' '224 bhp'
 '64.9 bhp' '148 bhp' '35.5 bhp' '89.75 bhp' '32.8 bhp' '91.72 bhp'
 '106 bhp' '98.97 bhp' '66.6 bhp' '86 bhp' '65.3 bhp' '98.82 bhp'
 '198.25 bhp' '38 bhp' '142 bhp' '132 bhp' '174.57 bhp' '178 bhp'
 '163.2 bhp' '203.2 bhp' '177.5 bhp' '175 bhp' '57 bhp' '80.84 bhp'
 '68.4 bhp' '167.67 bhp' '170.63 bhp' '52 bhp' '149.5 bhp' '48.21 bhp'
 ' bhp' '201.1 bhp' '100.5 bhp' '144 bhp' '194.4 bhp' '168.7 bhp'
 '104.5 bhp' '103.26 bhp' '116.4 bhp' '98.79 bhp' '80.9 bhp' '58.3 bhp'
 '272 bhp' '235 bhp' '167.62 bhp' '170.30 bhp' '139.46 bhp' '158 bhp'
 '110.5 bhp' '82.5 bhp' '141.1 bhp' '38.4 bhp' '197.2 bhp' '161 bhp'
 '194 bhp' '122.4 bhp' '134.10 bhp' '60.2 bhp' '134 bhp' '203 bhp'
 '135.1 bhp']
max_power
74 bhp       0.047643
81.80 bhp    0.027802
88.5 bhp     0.025780
67 bhp       0.020852
46.3 bhp     0.020473
               ...
80.9 bhp     0.000126
58.3 bhp     0.000126
272 bhp      0.000126
203 bhp      0.000126
135.1 bhp    0.000126
Name: proportion, Length: 322, dtype: float64

Column: torque
Cardinality: 441
['190Nm@ 2000rpm' '250Nm@ 1500-2500rpm' '12.7@ 2,700(kgm@ rpm)'
 '22.4 kgm at 1750-2750rpm' '11.5@ 4,500(kgm@ rpm)' '113.75nm@ 4000rpm'
 '7.8@ 4,500(kgm@ rpm)' '59Nm@ 2500rpm' '170Nm@ 1800-2400rpm'
 '160Nm@ 2000rpm' '248Nm@ 2250rpm' '78Nm@ 4500rpm' nan '84Nm@ 3500rpm'
 '115Nm@ 3500-3600rpm' '200Nm@ 1750rpm' '62Nm@ 3000rpm'
 '219.7Nm@ 1500-2750rpm' '114Nm@ 3500rpm' '115Nm@ 4000rpm' '69Nm@ 3500rpm'
 '172.5Nm@ 1750rpm' '6.1kgm@ 3000rpm' '114.7Nm@ 4000rpm' '60Nm@ 3500rpm'
 '90Nm@ 3500rpm' '151Nm@ 4850rpm' '104Nm@ 4000rpm' '320Nm@ 1700-2700rpm'
 '250Nm@ 1750-2500rpm' '145Nm@ 4600rpm' '146Nm@ 4800rpm'
 '343Nm@ 1400-3400rpm' '200Nm@ 1400-3400rpm' '200Nm@ 1250-4000rpm'
 '400Nm@ 2000-2500rpm' '138Nm@ 4400rpm' '360Nm@ 1200-3400rpm'
 '200Nm@ 1200-3600rpm' '380Nm@ 1750-2500rpm' '173Nm@ 4000rpm'
 '400Nm@ 1750-3000rpm' '400Nm@ 1400-2800rpm' '200Nm@ 1750-3000rpm'
 '111.7Nm@ 4000rpm' '219.6Nm@ 1500-2750rpm' '112Nm@ 4000rpm'
 '250Nm@ 1500-3000rpm' '130Nm@ 4000rpm' '205Nm@ 1750-3250rpm'
 '280Nm@ 1350-4600rpm' '99.04Nm@ 4500rpm' '77Nm@ 3500rpm' '110Nm@ 3750rpm'
 '153Nm@ 3800rpm' '113.7Nm@ 4000rpm' '114Nm@ 4000rpm' '113Nm@ 4200rpm'
 '101Nm@ 3000rpm' '290Nm@ 1800-2800rpm' '120Nm@ 4250rpm'
 '250Nm@ 1500~4500rpm' '96 Nm at 3000 rpm' '360Nm@ 1750-2800rpm'
 '135Nm@ 2500rpm' '259.8Nm@ 1900-2750rpm' '200Nm@ 1900rpm'
 '259.9Nm@ 1900-2750rpm' '91Nm@ 4250rpm' '96.1Nm@ 3000rpm'
 '109Nm@ 4500rpm' '400nm@ 1750-3000rpm' '202Nm@ 3600-5200rpm'
 '430Nm@ 1750-2500rpm' '347Nm@ 4300rpm' '382nm@ 1750-2250rpm'
 '620Nm@ 1600-2400rpm' '400Nm@ 1750-2500rpm' '250@ 1250-5000rpm'
 '500Nm@ 1600-1800rpm' '250Nm@ 1600-3600rpm' '400Nm' '550Nm@ 1750-2750rpm'
 '490Nm@ 1600rpm' '250 Nm at 2750 rpm' '177.5Nm@ 4700rpm'
 '170Nm@ 1750-4000rpm' '300Nm@ 1200-4000rpm' '300Nm@ 1200-1400rpm'
 '260Nm@ 1500-2750rpm' '213Nm@ 4500rpm' '224Nm@ 4000rpm' '640Nm@ 1740rpm'
 '113Nm@ 4500rpm' '95Nm@ 3000-4300rpm' '13.1kgm@ 4600rpm'
 '205Nm@ 1800-2800rpm' '71Nm@ 3500rpm' '190Nm@ 1750-3000rpm'
 '146Nm at 4800 rpm' '14.9 KGM at 3000 RPM' '115Nm@ 3200rpm'
 '117nm@ 4000rpm' '320Nm@ 1500-3000rpm' '72Nm@ 4386rpm'
 '11.4 kgm at 4,000 rpm' '140Nm@ 1500-4000rpm' '134Nm@ 4000rpm'
 '150Nm@ 4500rpm' '340Nm@ 1800-3250rpm' '240Nm@ 1600-2800rpm'
 '330Nm@ 1600-2800rpm' '12.5@ 3,500(kgm@ rpm)' '110Nm@ 4800rpm'
 '111.8Nm@ 4000rpm' '11.8@ 3,200(kgm@ rpm)' '135.4Nm@ 2500rpm'
 '300Nm@ 1750-2500rpm' '190.25nm@ 1750-2250rpm' '140Nm@ 1800-3000rpm'
 '20.4@ 1400-3400(kgm@ rpm)' '247Nm@ 1800-2000rpm' '223Nm@ 1600-2200rpm'
 '180 Nm at 1440-1500rpm' '195Nm@ 1400-2200rpm' '154.9Nm@ 4200rpm'
 '114.73Nm@ 4000rpm' '160Nm@ 1500-2750rpm' '108Nm@ 4400rpm'
 '190.24nm@ 1750-2250rpm' '200Nm@ 2000-3500rpm' '420Nm@ 1400-2600rpm'
 '100Nm@ 2700rpm' '51Nm@ 4000rpm' '250Nm@ 1250-5300rpm' '132Nm@ 3000rpm'
 '350Nm@ 1500-2750rpm' '218Nm@ 4200rpm' '14.9@ 3,000(kgm@ rpm)'
 '24@ 1,900-2,750(kgm@ rpm)' '13.5@ 2,500(kgm@ rpm)' '85Nm@ 3000rpm'
 '74.5Nm@ 4000rpm' '160Nm@ 1750rpm' '180.4Nm@ 1750-2500rpm'
 '230Nm@ 1500-2500rpm' '113.75Nm@ 4000rpm' '219.66nm@ 1500-2750rpm'
 '245Nm@ 1750rpm' '360Nm@ 1400-3200rpm' '320Nm@ 2000rpm'
 '135 Nm at 2500  rpm ' '24 KGM at 1900-2750 RPM' '190Nm@ 1750-2250rpm'
 '204Nm@ 2000-2750rpm' '14.3@ 1,800-3,000(kgm@ rpm)' '250nm@ 1500-2750rpm'
 '125Nm@ 2000rpm' '172Nm@ 4300rpm' '150Nm@ 1750rpm' '102Nm@ 4000rpm'
 '85Nm@ 2500rpm' '8.5@ 2,500(kgm@ rpm)' '180Nm@ 1440-1500rpm'
 '106.5Nm@ 4400rpm' '108.5Nm@ 5000rpm' '350Nm@ 1750-2500rpm'
 '144.15nm@ 4500rpm' '104Nm@ 4400rpm' '99Nm@ 4500rpm' '200Nm@ 2000rpm'
 '280Nm@ 1800-2800rpm' '142.5Nm@ 1750rpm' '140Nm@ 4400rpm'
 '115@ 2,500(kgm@ rpm)' '196Nm@ 5000rpm' '260 Nm at 1800-2200 rpm'
 '9.8@ 3,000(kgm@ rpm)' '209Nm@ 2000rpm' '135 Nm at 2500 rpm'
 '140Nm@ 4200rpm' '220Nm at 1400-2600 rpm' '48Nm@ 3000rpm'
 '171Nm@ 1800rpm' '277.5Nm@ 1700-2200rpm' '215Nm@ 3600rpm'
 '219.6Nm@ 1750-2750rpm' '195Nm@ 1440-2200rpm' '13@ 2,500(kgm@ rpm)'
 '180Nm@ 2000rpm' '200Nm@ 1400-2200rpm' '380Nm(38.7kgm)@ 2500rpm'
 '110Nm@ 4400rpm' '72Nm@ 4388rpm' '263.7Nm@ 2500rpm' '320Nm@ 1600-2800rpm'
 '25.5@ 1,500-3,000(kgm@ rpm)' '16.3@ 2,000(kgm@ rpm)'
 '190 Nm at 1750 rpm ' '94.14Nm@ 3500rpm' '12@ 3,500(kgm@ rpm)'
 '113Nm@ 5000rpm' '280Nm@ 2400-2800rpm' '96Nm@ 3500rpm'
 '16@ 2,000(kgm@ rpm)' '320Nm@ 1750-3000rpm' '114.73nm@ 4000rpm'
 '320Nm@ 1750-2500rpm' '138nm@ 4400rpm' '190Nm@ 1750rpm' '789Nm@ 2250rpm'
 '259.87Nm@ 1900-2750rpm' '205Nm@ 1750rpm' '436.39Nm@ 1800-2500rpm'
 '182.5Nm@ 1500-1800rpm' '90.3Nm@ 4200rpm' '12.5@ 2,500(kgm@ rpm)'
 '215Nm@ 1750-3000rpm' '215Nm@ 1750-3000' '305Nm@ 2000rpm'
 '540Nm@ 2000rpm' '327Nm@ 2600rpm' '300Nm@ 1600-3000rpm'
 '620Nm@ 2000-2500rpm' '450Nm@ 1600-2400rpm' '19@ 1,800(kgm@ rpm)'
 '9.2@ 4,200(kgm@ rpm)' '145@ 4,100(kgm@ rpm)' '51Nm@ 4000+/-500rpm'
 '110Nm@ 3000rpm' '148Nm@ 3500rpm' '116Nm@ 4750rpm'
 '48@ 3,000+/-500(NM@ rpm)' '148Nm@ 4000rpm' '222Nm@ 4300rpm'
 '135.3Nm@ 5000rpm' '98Nm@ 1600-3000rpm' '170Nm@ 1400-4500rpm'
 '343Nm@ 1400-2800rpm' '402Nm@ 1600-3000rpm' '113Nm@ 3300rpm'
 '99.07Nm@ 4500rpm' '210nm@ 1600-2200rpm' '190 Nm at 1750  rpm '
 '32.1kgm@ 2000rpm' '224nm@ 1500-2750rpm' '400nm@ 1750-2500rpm'
 '215Nm@ 1750-2500rpm' '25@ 1,800-2,800(kgm@ rpm)' '197Nm@ 1750rpm'
 '136.3Nm@ 4200rpm' '470Nm@ 1750-2500rpm' '11@ 3,000(kgm@ rpm)'
 '142Nm@ 4000rpm' '145Nm@ 4100rpm' '320Nm@ 1500-2800rpm'
 '123Nm@ 1000-2500rpm' '218Nm@ 1400-2600rpm' '510@ 1600-2400'
 '220Nm@ 1500-2750rpm' '380Nm@ 2000rpm' '104Nm@ 3100rpm' '292Nm@ 2000rpm'
 '20@ 3,750(kgm@ rpm)' '46.5@ 1,400-2,800(kgm@ rpm)' '380Nm@ 2500rpm'
 '15@ 3,800(kgm@ rpm)' '136Nm@ 4250rpm' '228Nm@ 4400rpm' '149Nm@ 4500rpm'
 '187Nm@ 2500rpm' '146Nm@ 3400rpm' '8.6@ 3,500(kgm@ rpm)'
 '219.7Nm@ 1750-2750rpm' '190Nm@ 2000-3000' '450Nm@ 2000rpm'
 '300Nm@ 2000rpm' '230Nm@ 1800-2000rpm' '42@ 2,000(kgm@ rpm)'
 '110Nm@ 3000-4300rpm' '110(11.2)@ 4800' '330Nm@ 1800rpm'
 '225Nm@ 1500-2500rpm' '380Nm@ 1750-2750rpm' '28.3@ 1,700-2,200(kgm@ rpm)'
 '259.88Nm@ 1900-2750rpm' '580Nm@ 1400-3250rpm' '400 Nm /2000 rpm'
 '127Nm@ 3500rpm' '300Nm@ 1500-2500rpm' '132.3Nm@ 4000rpm'
 '113nm@ 4400rpm' '151NM@ 4850rpm' '153Nm@ 3750-3800rpm'
 '10.7@ 2,500(kgm@ rpm)' '124.6Nm@ 3500rpm' '78Nm@ 3500rpm'
 '219.9Nm@ 1750-2750rpm' '420.7Nm@ 1800-2500rpm' '130Nm@ 3000rpm'
 '424Nm@ 2000rpm' '130@ 2500(kgm@ rpm)' '99.8Nm@ 2700rpm'
 '113Nm@ 4,500rpm' '11.2@ 4,400(kgm@ rpm)' '240Nm@ 1850rpm'
 '16.1@ 4,200(kgm@ rpm)' '320Nm@ 1750-2700rpm' '115Nm@ 4500rpm'
 '245Nm@ 4000rpm' '321Nm@ 1600-2400rpm' '619Nm@ 1600-2400rpm'
 '380Nm@ 1750-3000rpm' '560Nm@ 1500rpm' '230Nm@ 1500-2250rpm'
 '90Nm@ 2650rpm' '260Nm@ 1800-2200rpm' '600Nm@ 2000rpm'
 '259.87nm@ 1500-3000rpm' '16.6@ 4,500(kgm@ rpm)' '219.66NM@ 1500-2750rpm'
 '12.5@ 3,000(kgm@ rpm)' '620Nm@ 1500-2500rpm' '250Nm@ 1500-4500rpm'
 '14.9@ 3,400(kgm@ rpm)' '25.5@ 1,900(kgm@ rpm)' '33.7@ 1,800(kgm@ rpm)'
 '285Nm@ 2400-4000rpm' '10.7@ 2,600(kgm@ rpm)' '250Nm@ 1000-2000rpm'
 '240Nm@ 1750rpm' '226Nm@ 4400rpm' '510Nm@ 1600-2800rpm'
 '259.87NM@ 1500-3000rpm' '155 Nm at 1600-2800 rpm' '240Nm@ 2000rpm'
 '103Nm@ 4500rpm' '13.5@ 4,800(kgm@ rpm)' '400Nm@ 1750-2750rpm'
 '175Nm@ 1500-4100rpm' '72.9Nm@ 2250rpm' '135.4Nm@ 2500' '245Nm@ 5000rpm'
 '57Nm@ 2500rpm' '96Nm@ 2500rpm' '215nm@ 1750-2500rpm'
 '10.4@ 3,200(kgm@ rpm)' '128Nm@ 3100rpm' '102Nm@ 2600rpm'
 '131Nm@ 4400rpm' '11.4@ 4,000(kgm@ rpm)' '250Nm@ 4250rpm'
 '343Nm@ 1600-2800rpm' '185Nm@ 1750-2750rpm' '12@ 2500(kgm@ rpm)'
 '12.4@ 2,600(kgm@ rpm)' '170Nm@ 4200rpm' '176Nm@ 1500rpm'
 '380NM@ 1800-2800rpm' '250Nm@ 1600-2000rpm' '24.5@ 3,500-4,500(kgm@ rpm)'

In [13]:
df.duplicated().sum()

np.int64(1202)

In [15]:
df =df.drop_duplicates()
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0

In [16]:
df.duplicated().sum()

np.int64(0)

In [5]:
X = df.drop(columns='selling_price')
Y = df.selling_price.copy()
print(X.shape, Y.shape)

(8128, 12) (8128,)

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(6502, 12) (6502,)
(1626, 12) (1626,)

In [18]:
num_cols = X_train.select_dtypes(include='number').columns.tolist()
cat_cols = [col for col in X_train.columns if col not in num_cols]
print(num_cols)
print(cat_cols)

['year', 'km_driven', 'mileage', 'engine', 'max_power', 'torque', 'seats']
['name', 'fuel', 'seller_type', 'transmission', 'owner']

In [12]:
num_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy = 'median')),
    ('scaler', StandardScaler())
])

cat_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer(transformers=[
    ('num', num_pipe, num_cols),
    ('cat', cat_pipe, cat_cols)

])

regressor = RandomForestRegressor(
    n_estimators=10, max_depth=5, random_state=42
)

rf_model = Pipeline(steps=[
    ('pre', preprocessor),
    ('reg', regressor)
])
rf_model.fit(X_train, Y_train)

Pipeline(steps=[('pre',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['year', 'km_driven',
                                                   'mileage', 'engine',
                                                   'max_power', 'torque',
                                                   'seats']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['name', 'fuel',
                                                   'seller_type',
                                                   'transmission',
                                                   'owner'])])),
                ('reg',
                 RandomForestRegressor(max_depth=5, n_estimators=10,
                                       random_state=42))])

In [17]:
Y_train_pred = rf_model.predict(X_train)
train_rmse = root_mean_squared_error(Y_train, Y_train_pred)
print(f'Train RMSE: {train_rmse:,.3f}')
Y_test_pred = rf_model.predict(X_test)
test_rmse = root_mean_squared_error(Y_train, Y_train_pred)
print(f'Test RMSE: {test_rmse:,.3f}')

Train RMSE: 175,239.635
Test RMSE: 175,239.635